xl: xml.c \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/stdio.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/features.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/uClibc_config.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/uClibc_arch_features.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/sys/cdefs.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/cross-tools/lib/gcc/arm-linux-uclibcgnueabi/4.2.4/include/stddef.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/types.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/wordsize.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/kernel_types.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/typesizes.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/pthreadtypes.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/sched.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/uClibc_stdio.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/wchar.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/wchar.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/uClibc_mutex.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/pthread.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/sched.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/time.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/time.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/uClibc_clk_tck.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/signal.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/sigset.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/initspin.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/sigthread.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/uClibc_pthread.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/cross-tools/lib/gcc/arm-linux-uclibcgnueabi/4.2.4/include/stdarg.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/stdio_lim.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/unistd.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/posix_opt.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/confname.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/getopt.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/stdlib.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/sys/types.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/endian.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/endian.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/sys/select.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/select.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/sys/sysmacros.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/alloca.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/string.h \
  common.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/sys/socket.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/sys/uio.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/uio.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/socket.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/cross-tools/lib/gcc/arm-linux-uclibcgnueabi/4.2.4/include/limits.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/cross-tools/lib/gcc/arm-linux-uclibcgnueabi/4.2.4/include/syslimits.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/limits.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/posix1_lim.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/local_lim.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/linux/limits.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/uClibc_local_lim.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/posix2_lim.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/sockaddr.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/asm/socket.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/asm/sockios.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/netinet/in.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/stdint.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/in.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/byteswap.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/arpa/inet.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/iconv.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/errno.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/errno.h \
  /opt/toolchain/gcc-4.2.4-uClibc-0.9.29-toolchain/usr/include/bits/errno_values.h \
  list.h xml.h
